---
provisioner:
  name: chef_solo
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.2
  driver_config:
    box: debian-7.2
    box_url: https://dl.dropboxusercontent.com/u/197673519/debian-7.2.0.box

suites:
  - name: default
    run_list:
      - recipe[lsyncd_test::integration]
    attributes: {
      "lsyncd": {
        "interval": 1
      }
    }
